- lib/support/gds/user_facing_components.rb
- This request came from https://govuk.zendesk.com/agent/tickets/961823.
Before:
After:
> Add a radio button for a Specialist Publisher fault

- Gemfile
- Gemfile.lock
- app/views/layouts/application.html.erb
Include IP-anonymised universal analytics within support app https://github.com/alphagov/govuk_admin_template/pull/59
> Bump admin gem to 2.1.0

- Gemfile
- Gemfile.lock
- Rakefile
- app/assets/javascripts/application.js
- app/assets/javascripts/modules/calendar.js
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/calendar.scss
- app/controllers/anonymous_feedback_controller.rb
- app/helpers/date_filter_helper.rb
- app/presenters/anonymous_feedback_presenter.rb
- app/views/anonymous_feedback/index.html.erb
- app/views/campaign_requests/_request_details.html.erb
- app/views/content_advice_requests/_request_details.html.erb
- app/views/layouts/application.html.erb
- app/views/remove_user_requests/_request_details.html.erb
- app/views/support/_time_constraint.html.erb
- spec/controllers/anonymous_feedback_controller_spec.rb
- spec/features/feedex_spec.rb
- spec/features/user_satisfaction_survey_spec.rb
- spec/helpers/date_filter_helper_spec.rb
- spec/javascripts/spec/calendar.spec.js
- spec/javascripts/support/jasmine.yml
- spec/javascripts/support/jasmine_helper.rb
Users can now pick dates from calendar. Added jQuery UI date picker, jasmine for Javascript testing. Parsing date parameters through to support-api.
cc @boffbowsh @fofr @benilovj
> Add date picker

- config/initializers/pp_data_in.rb
The app no longer talks to the PP (all uploads happen in support-api).
> Remove initialiser for PP

- app/helpers/application_helper.rb
- app/views/anonymous_feedback/organisations/show.html.erb
- config/breadcrumbs.rb
* Add correct breadcrumb for org pages
* Correctly indicate "Feedback" link in header as selected
> Tweak organisation summary breadcrumbs

- Gemfile
- Gemfile.lock
- app/controllers/anonymous_feedback/export_requests_controller.rb
- app/views/anonymous_feedback/index.html.erb
- app/views/layouts/application.html.erb
- config/routes.rb
- spec/controllers/anonymous_feedback/export_requests_controller_spec.rb
Add Export to CSV button
Add GA tracking to the flash message
TODO:
> Add controller for requesting/retrieving CSVs

- app/views/anonymous_feedback/index.html.erb
Missed this. Need to add much better test coverage for this functionality.
> Ensure we can filter by date for organisation

- app/views/anonymous_feedback/index.html.erb
> Fix incorrect URL parameter being sent

- app/views/create_or_change_user_requests/_requested_user_details.html.erb
Change copy to reflect the fact that the person who fills in the form
is requesting changes for someone else.
cc @fofr 
[Trello](https://trello.com/c/pi5NbNsj/119-update-the-create-or-change-a-user-account-form-in-support-app-small)
> Harmonise copy

- app/views/create_or_change_user_requests/_request_details.html.erb
> Fix inadvertently broken HTML

- app/views/support/emergency_contact_details.html.erb
call a member of the GOV.UK escalations team instead of the GOV.UK operations manager
> Update copy 

- app/controllers/changes_to_publishing_apps_requests_controller.rb
- app/views/changes_to_publishing_apps_requests/_guidance.html.erb
- app/views/changes_to_publishing_apps_requests/_request_details.html.erb
- lib/support/requests/changes_to_publishing_apps_request.rb
- lib/zendesk/ticket/changes_to_publishing_apps_request_ticket.rb
- spec/features/changes_to_publishing_apps_requests_spec.rb
[Trello card](https://trello.com/c/DOzxDgNC/32-amend-product-request-form)
The form is now really closely focused around new product requests, so we should make a couple of changes to it to help with this focus.
> Update 'new feature' form

- Gemfile
- Gemfile.lock
- spec/workers/zendesk_ticket_worker_spec.rb
[Trello card](https://trello.com/c/GgAfSAFK/42-harden-the-zendesk-integration-and-improve-monitoring)
> Add worker spec for 302 response from Zendesk

- lib/support/permissions/ability.rb
- spec/features/analytics_requests_spec.rb
- spec/features/content_advice_requests_spec.rb
- spec/features/emergency_contact_details_spec.rb
- spec/features/unpublish_content_requests_spec.rb
- spec/models/support/requests/permissions_spec.rb
[Trello card](https://trello.com/c/COcqtgck/50-modify-support-permissions)
> Modified permissions

- lib/support/requests/campaign_request.rb
- spec/features/campaign_requests_spec.rb
This form is just for new campaigns now (not for ongoing support).
> Updated title and description

- app/views/support/emergency_contact_details.html.erb
Changed 'content lead' to 'senior member of content team' (it's not just the content leads anymore).
> Copy change

- app/views/content_change_requests/_request_details.html.erb
- spec/features/content_change_requests_spec.rb
For: [Trello card](https://trello.com/c/gdX8tv08/186-add-new-field-to-content-request-form)
Rename field for adding urls from:
'Does this affect any other URLs?'
to
'Does this affect any other URLs (including any existing Welsh translations that need to be updated). Put each new URL on a new line.'
This will prompt those making content request changes to check if there's a Welsh version.
> Rename field in content change request form

- app/views/support/emergency_contact_details.html.erb
The last updated date hasn't updated since 2015. I don't see a need for it.
> Deleted 'last updated'

- app/controllers/campaign_requests_controller.rb
- app/models/support/gds/campaign.rb
- app/models/zendesk/ticket/campaign_request_ticket.rb
- app/views/campaign_requests/_request_details.html.erb
- spec/features/campaign_requests_spec.rb
- spec/models/support/gds/campaign_spec.rb
For: https://trello.com/c/eOI3uArg/37-1-changes-to-support-form-for-campaign-requests
Adds new fields to the "Request a new campaign form" and reformulates questions.
> Change campaign request form

- app/models/support/gds/user_facing_components.rb
https://trello.com/c/sDIsMglD/258-add-content-publisher-to-list-of-apps-in-support-form
> Add Content Publisher (beta) to support form options

- app/controllers/eu_exit_business_readiness_requests_controller.rb
- app/models/support/navigation/section_groups.rb
- app/models/support/permissions/ability.rb
- app/models/support/requests/eu_exit_business_readiness_request.rb
- app/models/zendesk/ticket/eu_exit_business_readiness_ticket.rb
- app/views/eu_exit_business_readiness_requests/_request_details.html.erb
The facet values are hard coded to avoid extra logic in a form that we hope won't be long lasting.
[Trello Card](https://trello.com/c/S9wcDkvG/167-capture-content-for-the-eu-exit-finder)
> Add form for new EU Exit Business Readiness content

- app/controllers/eu_exit_business_readiness_requests_controller.rb
- app/models/support/requests/eu_exit_business_readiness_request.rb
- app/models/zendesk/ticket/eu_exit_business_readiness_ticket.rb
- app/views/eu_exit_business_readiness_requests/_request_details.html.erb
This includes various content updates to the EU Exit Business Finder support form as requested by the content designers.
[Trello Card](https://trello.com/c/S9wcDkvG/167-capture-content-for-the-eu-exit-finder)
> EU Exit Business Finder Updates

- app/models/support/requests/eu_exit_business_readiness_request.rb
Requested by the content designers.
> Update the description of the business readiness form

- app/models/support/requests/eu_exit_business_readiness_request.rb
- app/views/eu_exit_business_readiness_requests/_request_details.html.erb
More updates as requested by the content designers! :)
> Further updates to the business finder form

- app/views/eu_exit_business_readiness_requests/_request_details.html.erb
This was missed in the previous PR #543.
> Remove unnecessary line about the business finder

- app/controllers/support_controller.rb
- app/views/support/emergency_contact_details.html.erb
- config/emergency_contact_details.json
Depends on https://github.com/alphagov/govuk-secrets/pull/530
**Please ensure Puppet has been deployed to add contact details to app env before deploying this**
> Add verify contact details

- app/views/support/emergency_contact_details.html.erb
Add bullets to office hour and out of hours content support sections telling depts to leave a message if there's no answer.
> Tell people to leave a message

- .gitignore
- Gemfile
- Gemfile.lock
- lib/tasks/lint.rake
- spec/support/capybara.rb
- spec/support/govuk_test.rb
Also updates the `cancancan` Gem.
>  Configure tests using govuk_test

- Gemfile
- Gemfile.lock
This reverts commit b18f58c3daea21d98641e8fcef21b782508a8e89.
> Revert "Bundle update cancancan"

- app/controllers/campaign_requests_controller.rb
- app/models/support/gds/campaign.rb
- app/models/zendesk/ticket/campaign_request_ticket.rb
- app/views/campaign_requests/_request_details.html.erb
- spec/features/campaign_requests_spec.rb
- spec/models/support/gds/campaign_spec.rb
Add site_title and site_tagline
Change the label for site_metadescription
Trello: https://trello.com/c/cNfljgRZ/1114-update-required-fields-on-campaign-application-form
> Update campaign application form

- app/views/campaign_requests/_request_details.html.erb
* Add missing "
* Move site metadescription
* Change help block text for description field
Trello: https://trello.com/c/cNfljgRZ/1114-update-required-fields-on-campaign-application-form
> More tweaks to campaign form.

- Gemfile
- config/environments/production.rb
- config/initializers/current_release_sha.rb
- config/initializers/filter_parameter_logging.rb
- config/initializers/formtastic.rb
- config/initializers/gds-sso.rb
- config/initializers/gds_zendesk.rb
- config/initializers/inflections.rb
- config/routes.rb
These were missed in https://github.com/alphagov/support/pull/669.
> Auto-fix linting issues

- Rakefile
- config/initializers/gds-sso.rb
- script/cucumber
- script/rails
This is depended on by https://github.com/alphagov/govuk-jenkinslib/pull/66.
> Make entire repository pass Rubocop linting

- README.md
> Fix incorrect link to support-api

- Gemfile
- Gemfile.lock
- spec/rails_helper.rb
https://trello.com/c/epNWudCR/176-write-an-rfc-for-continuous-deployment-and-seek-review
We should always monitor the amount of code that is exercised when
we run our tests.
> Use SimpleCov to monitor code coverage

- config/routes.rb
https://trello.com/c/YPh5Epuc/2433-5-enable-continuous-deployment-for-support-app
> Add /healthcheck route

- .github/pull_request_template.md
https://trello.com/c/YPh5Epuc/2433-5-enable-continuous-deployment-for-support-app
> Add PR template warning about CD

- config/initializers/content_security_policy.rb
Should have been done in #1010
> Run 'rails app:update'

- .dockerignore
- Dockerfile
- config/puma.rb
- config/sidekiq.yml
Add Dockerfile which is standard we use for Ruby Apps
Add .dockerignore to keeps image clean
adds Puma via govuk_app_config
https://trello.com/c/44ebF691/1026-publishing-journey-apps-migrations
> Dockerised app to meet replatforming standards.

- app/views/unpublish_content_requests/_request_details.html.erb
https://trello.com/c/CkRb8XcT/3003-audit-usage-of-alphagovcouk-domain-2
> We don't use the alphagov.co.uk domain anymore

- app/controllers/campaign_requests_controller.rb
- app/models/support/gds/campaign.rb
- app/models/zendesk/ticket/campaign_request_ticket.rb
- app/views/campaign_requests/_request_details.html.erb
- spec/features/campaign_requests_spec.rb
- spec/models/support/gds/campaign_spec.rb
> Reinstate question in campaign form

- config/application.rb
Fixes assets not being served correctly on k8s
See also: https://github.com/alphagov/manuals-publisher/pull/2004
https://trello.com/c/VuxjcRPI/1096-user-journey-make-a-support-request
> Include app name in the rails assets path

- app/assets/stylesheets/application.scss
- app/controllers/content_change_requests_controller.rb
- app/models/support/requests/content_change_request.rb
- app/models/support/requests/time_constraint.rb
- app/models/support/requests/with_time_constraint.rb
- app/models/zendesk/ticket/content_change_request_ticket.rb
- app/models/zendesk/zendesk_ticket.rb
- app/views/content_change_requests/_request_details.html.erb
- app/views/layouts/application.html.erb
- app/views/support/_collaborators.html.erb
- app/views/support/_time_constraint.html.erb
- app/views/support/acknowledge.html.erb
- spec/features/content_change_requests_spec.rb
- spec/models/support/requests/time_constraint_spec.rb
- spec/support/app_actions.rb
- All form updates have been done
- The only thing remaining to do is the mapping on Zendesk.
```
- Custom “title” field
- Custom “reason for change” field
- Custom “subject area” field
- Custom “needs Welsh” field, based on “Welsh URL” field being filled
- “What’s the new or different information”, in Zendesk body
- “Why is change needed”, in Zendesk body
- Custom “Deadline” field (this may already happen)
- Custom “Not before” field (this may already happen)
- “Reason for deadline”, in Zendesk body
- “Who needs a copy of this request”, put into Zendesk cc field (this already happens)
```
Details of change request are added to the following doc:
https://docs.google.com/document/d/1s0OoBexbHXnDIx554EyudsdAYpAKI7C1p4VFBvqkW9Q/edit
Content designers want us to improve [the GOV.UK content …
> [DO NOT MERGE] Changes to content requests form in publisher

- app/models/support/requests/requester.rb
- spec/models/support/requests/requester_spec.rb
Use a more robust regex to check emails.
https://trello.com/c/oFWuEIyv/3318-improve-email-validation-in-support-app-3
> Improve email check regex

- Gemfile
- Gemfile.lock
- app/assets/config/manifest.js
- app/assets/javascripts/application.js
- app/assets/javascripts/es6-components.js
- app/views/layouts/application.html.erb
https://trello.com/c/qmPB0DEN/3581-upgrade-our-apps-to-v51-of-the-design-system-3
> Upgrade to govuk frontend 5.1

- app/views/campaign_requests/_request_details.html.erb
https://govuk.zendesk.com/agent/tickets/5892377
---
> Update 'Request a New Campaign' form

- app/views/content_data_feedback/_request_details.html.erb
This makes the situation clear to users and helps set expectations.
> Be clearer about Content Data feedback

- app/controllers/create_new_user_requests_controller.rb
- app/models/support/requests/create_new_user_request.rb
- app/models/zendesk/custom_field.rb
- app/models/zendesk/ticket/create_new_user_request_ticket.rb
- app/views/create_new_user_requests/_request_details.html.erb
- config/locales/en.yml
- config/zendesk/custom_fields_data.yml
- spec/controllers/create_new_user_requests_controller_spec.rb
- spec/features/create_new_user_requests_spec.rb
- spec/models/support/requests/create_new_user_request_spec.rb
- spec/models/zendesk/custom_field_spec.rb
- spec/models/zendesk/ticket/create_new_user_request_ticket_spec.rb
⚠️ Deployment date: late on Monday, 28 October or first thing on Tuesday morning 29 October. ⚠️ 
This is making changes to the ‘Create new user’ support form, as outlined in this [document](https://docs.google.com/document/d/1xzrD0R8n5WbsBo7XyYIlGx5E6rPUHNMGp5i4OXwhj1Q/edit#heading=h.iiwyson5ok7b):
- Adding User's email hint
- Updating 'Does the user need training to access Whitehall Publisher?' as below:
- update the question
- add hint
- update radio buttons' description
- add a radio button
- Update "Who needs a copy of this request?" hint
| Before   | After |
| -------- | ------- |
| <img width="547" alt="Screenshot 2024-10-02 at 17 42 43" src="https://github.com/user-attachments/assets/2681523e-dec7-4e55-b74e-eef1e6c174e2"> | <img width="453" alt="Screenshot 2024-10-02 at 17 48 13" …
> Update 'Create a new user' request form

- app/controllers/create_new_user_requests_controller.rb
- app/views/create_new_user_requests/_request_details.html.erb
- spec/controllers/create_new_user_requests_controller_spec.rb
- spec/models/support/requests/create_new_user_request_spec.rb
[Trello](https://trello.com/c/IN20Asaz/1634-updates-to-the-create-new-user-support-form)
A few small tidy ups of create new user request code before updating the form in #1665
> Tidy up create new user request

- app/controllers/remove_user_requests_controller.rb
- app/models/support/requests/remove_user_request.rb
- app/views/remove_user_requests/_request_details.html.erb
- spec/features/remove_user_requests_spec.rb
Most of the work is in the .erb file.
I also put a full stop on the end of one string, for consistency with other forms.
Some CSS selectors in the tests needed adjusting.
> Designsystemise Remove User form
