alphagov/support

Gemfile
Gemfile.lock

This picks up the latest 'zendesk_api' gem, which fixes
https://errbit.preview.alphagov.co.uk/apps/5319f4d40da115d7a90004fe/problems/5526b2990da1157bfa0008be
/cc @issyl0

Upgrade gds_zendesk to 1.0.4

---

app/assets/stylesheets/application.scss
app/views/anonymous_feedback/_anonymous-contact.html.erb
app/views/anonymous_feedback/_results.html.erb
app/views/anonymous_feedback/explore/new.html.erb
app/views/anonymous_feedback/index.html.erb
lib/support/navigation/feedex_section.rb
spec/features/feedex_spec.rb
spec/features/user_satisfaction_survey_spec.rb
spec/support/app_actions.rb

* Use readable date formats
* Prevent dates from wrapping to new lines
* Use better column headings
* Use shorter, more legible page titles
cc @rivalee @benilovj 
Before
After
Before
After

Tweak feedback explorer table and page headings

---

config/environments/production.rb

This is the default configuration in new Rails 4 apps. Without this
setting, Rails throws deprecation warnings that in Rails 5, the log
level is set to :debug in production if left unset.

Explicitly set log level to info in prod

---

app/views/anonymous_feedback/explore/new.html.erb
lib/support/requests/anonymous/explore.rb
spec/controllers/anonymous_feedback/explore_controller_spec.rb
spec/features/feedex_spec.rb
spec/models/support/requests/anonymous/explore_by_url_spec.rb

Allow full URLs with http and https, as well as partial URLs beginning with gov.uk or www.gov.uk, URLs users have entered with a bad protocol, or simply the plain path itself – with or without leading slash.
The following inputs all give the same results page:
```
Valid
https://www.gov.uk/vat-rates
http://www.gov.uk/vat-rates
Invalid
http//www.gov.uk/vat-rates
https//:www.gov.uk/vat-rates
Short hand
www.gov.uk/vat-rates
gov.uk/vat-rates
/vat-rates
vat-rates
```
Also
* removes inline form validation – what the browser validation defines as a URL is too strict.
* adds examples to the form
cc @rivalee @benilovj

Be lenient in what the feedback explorer can receive in its URL field

---

app/views/anonymous_feedback/explore/new.html.erb

Make the form clearer and use a better explanation of where the feedback comes from.
https://tree.taiga.io/project/core-improvement-theme/us/9
cc @rivalee @benilovj 
(Future page features prototyped here: https://github.com/alphagov/support/commit/8289a88e4deba317811ce27c87fda75d8431580c#comments)

Improve feedex homepage

---

lib/support/requests/content_advice_request.rb
spec/features/content_advice_requests_spec.rb

Before this fix, the nature of the request was not being sent to Zendesk if
the user has picked their own reason.

Bugfix on content advice requests

---

Gemfile
Gemfile.lock

Bump version of 'formtastic-bootstrap' gem; this picks up a bugfix (https://github.com/mjbellantoni/formtastic-bootstrap/pull/119)
which is currently unreleased to rubygems.
Before:
After:

Fix label appearing twice on 'Request to unpublish content' form

---

app/controllers/analytics_requests_controller.rb
app/controllers/campaign_requests_controller.rb
app/controllers/content_advice_requests_controller.rb
app/controllers/content_change_requests_controller.rb
app/controllers/create_or_change_user_requests_controller.rb
app/controllers/foi_requests_controller.rb
app/controllers/general_requests_controller.rb
app/controllers/named_contacts_controller.rb
app/controllers/new_feature_requests_controller.rb
app/controllers/remove_user_requests_controller.rb
app/controllers/technical_fault_reports_controller.rb
app/controllers/unpublish_content_requests_controller.rb

Commit 83fab62 (which was included in #219) inadvertently
introduced a bug whereby any unexpected parameter in a POST submission
would result in a 500 error.
This was a serious problem because the 'feedback' app is submitting
requests with extra (unnecessary) fields for certain requests, including
the public support form requests and the FOI requests.
This change introduces strong params into all controller actions that
receive form submissions. Acceptable parameters are now explicitly whitelisted,
meaning that unexpected parameters are thrown away. The next step after this
is to stop the 'feedback' app from submitting unexpected params.

Introduce strong params for all incoming POST requests

---

app/views/anonymous_feedback/_anonymous-contact.html.erb
app/views/anonymous_feedback/_feedback.html.erb
app/views/anonymous_feedback/_results.html.erb
spec/features/feedex_spec.rb
spec/features/user_satisfaction_survey_spec.rb

Make the action/problem feedback more legible by
* removing visible labels
* capitalising the start of each action/problem
* visibly rendering the action as a heading for the problem
cc @benilovj @rivalee

Improve formatting of anonymous feedback

---

spec/controllers/anonymous_feedback_controller_spec.rb
spec/features/redirects_spec.rb

A small clean up to some of the specs' use of GdsApi request stubs.
A couple of these issues are caused by WebMock's need to have stubs explicitly cleared after use - i.e. later specs were relying on API request stubs from earlier specs. (We could try to explicitly clear stubs after use in a few different ways, if it was agreed to be worthwhile. An alternative is running the specs in a random order, as I did to find these problems this time.)
I haven't managed to get to the bottom of one of these issues. It seemed as though an API request stub from an earlier spec was being triggered from a later spec that had already performed its own request stub with the same URI. For now I've just changed their URIs to be unique. That is clearly not a long-term solution.

Stub requests in specs

---

app/helpers/referrer_helper.rb
spec/helpers/referrer_helper_spec.rb

For certain referrer URLs  eg `Taxed%20to%2`, `Rack::Utils.parse_query(uri.query)` throws an ArgumentError: `invalid %-encoding`.
Because this is mostly an enhancement to the table, rather than attempt to decode the query correctly, return a nil search term.
Interestingly, before Ruby 2.1 this URL would have thrown `URI::InvalidURIError` and the error would have been caught.
A discussion on the nuances of this issue can be found here:
https://github.com/rack/rack/issues/337
cc @benilovj @boffbowsh

Prevent invalid query strings in referrers from erroring

---

Gemfile
Gemfile.lock
app/controllers/anonymous_feedback/explore_controller.rb
spec/controllers/anonymous_feedback/explore_controller_spec.rb
spec/features/redirects_spec.rb
spec/support/app_actions.rb

Break link to Whitehall organisations API, preferring support api organisations list
Add the status of the organisation to the list if it’s not live
Default the selected organisation to the currently logged-in user's organisation

Add support for filtering orgs by acronym

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/sortable_table.scss
app/controllers/anonymous_feedback/organisations_controller.rb
app/presenters/organisation_summary_presenter.rb
app/views/anonymous_feedback/organisations/show.html.erb
spec/features/feedex_organisation_summary_spec.rb
spec/features/feedex_spec.rb
spec/presenters/organisation_summary_presenter_spec.rb
spec/support/app_actions.rb

* Make table header cells clickable and use them to sort the table by those columns
* Default to last 7 days sorting
* Add spec for browsing by organisation
Part of https://tree.taiga.io/project/core-improvement-theme/us/12?kanban-status=211675
cc @boffbowsh @benilovj

Add sorting to organisation summary table

---

app/assets/stylesheets/sortable_table.scss
app/views/anonymous_feedback/organisations/show.html.erb

On pages with long URLs the path column was stretching out and squishing the “X items” columns.
* Add a minimum width to prevent this

Keep items columns readable

---

app/views/anonymous_feedback/index.html.erb

At thin widths the container size wasn’t large enough to contain the form as well as the reset filter button.
* Give the form more space at medium page widths
* Keep the space the same at larger ones
Prevents:
cc @benilovj

Improve wrapping of date filter at small widths

---

Gemfile
Gemfile.lock

This picks up a fix for a bug that meant Zendesk ticket creation
failed silently if the Zendesk API suddenly started returning redirects.

Bump gds-zendesk gem to 1.0.5

---

app/controllers/anonymous_feedback/explore_controller.rb
spec/controllers/anonymous_feedback/explore_controller_spec.rb

When a URL is not present, the controller would render the `new` template but without going through the new method it wouldn’t have all the template variables it needed.
* Call the `new` method before rendering with a 422 status code
https://trello.com/c/OAJAO2RB/

Prevent empty URL searches from erroring

---

app/views/support/emergency_contact_details.html.erb

https://trello.com/c/lA8ulqDQ
The content team submitted some changes to the emergency contact details on the support form. Minor style amends and changes to out of hours coverage (days and times).

Emergency contact details updates

---

app/controllers/content_advice_requests_controller.rb
app/views/content_advice_requests/_request_details.html.erb
lib/support/requests/content_advice_request.rb
lib/zendesk/ticket/content_advice_request_ticket.rb
lib/zendesk/ticket/content_change_request_ticket.rb
lib/zendesk/ticket/new_feature_request_ticket.rb
lib/zendesk/zendesk_ticket.rb
lib/zendesk/zendesk_tickets.rb
spec/features/content_advice_requests_spec.rb
spec/features/content_change_requests_spec.rb
spec/features/new_feature_requests_spec.rb
spec/features/remove_user_requests_spec.rb
spec/models/support/requests/content_advice_request_spec.rb
spec/models/zendesk/ticket/content_advice_request_ticket_spec.rb

By moving the dates to the comment body, they're always displayed. At the moment, they're only displayed if the user turns on "Show all events".
This also includes a refactoring to use the TimeConstraint code for ContentAdviceRequests, which builds on the first commit. This second bit could be split off if needed.

Move dates to comment body

---

app/views/requests/new.html.erb

Cc field should not be the first field on support requests, but should be at the end of the form.
This was feedback from the content team on [this story](https://trello.com/c/pi5NbNsj/119-update-the-create-or-change-a-user-account-form-in-support-app-small).
Before
After
cc @benilovj

Move cc field to the bottom of requests

---

Gemfile
Gemfile.lock
lib/zendesk/zendesk_tickets.rb

This picks up the fix to the "Create or update user request"
form (the form submission broke in development).
This commit also involves removing the unused field mappings
refernce, as field mappings have been removed from `gds_zendesk`.
/cc @binaryberry

Update the 'gds_zendesk' gem to 2.0.0

---

app/assets/stylesheets/application.scss
app/controllers/create_or_change_user_requests_controller.rb
app/views/create_or_change_user_requests/_request_details.html.erb
app/views/support/_user_needs.html.erb
lib/support/gds/with_user_needs.rb
lib/support/requests/create_or_change_user_request.rb
lib/zendesk/ticket/create_or_change_user_request_ticket.rb
spec/controllers/create_or_change_user_requests_controller_spec.rb
spec/features/create_or_change_user_requests_spec.rb
spec/models/support/gds/with_user_needs_spec.rb
spec/models/support/requests/create_or_change_user_request_spec.rb

Change the copy and options for creating or changing a user account in the support app.
Users can now select either a type of Whitehall account, other permissions or both. This was reviewed and approved by Nick Cammel in the content team
Before
After
cc @benilovj @boffbowsh 
[Trello](https://trello.com/c/pi5NbNsj/119-update-the-create-or-change-a-user-account-form-in-support-app-small)

Update the 'create or change a user account' form in Support app

---

app/controllers/create_or_change_user_requests_controller.rb
app/views/create_or_change_user_requests/_requested_user_details.html.erb
lib/support/gds/requested_user.rb
lib/zendesk/ticket/create_or_change_user_request_ticket.rb
spec/controllers/create_or_change_user_requests_controller_spec.rb
spec/features/create_or_change_user_requests_spec.rb
spec/models/support/gds/requested_user_spec.rb

When deciding on granting user permissions, people need to know what previous training requesters have had.
Discussed design and copy with @fofr and Nick Cammel from the content team.
before
after
cc @fofr @boffbowsh 
[Trello](https://trello.com/c/pi5NbNsj/119-update-the-create-or-change-a-user-account-form-in-support-app-small)

Add training information to create or change user

---

app/helpers/feedex_helper.rb
app/presenters/anonymous_feedback_presenter.rb
app/views/anonymous_feedback/index.html.erb
spec/helpers/feedex_helper_spec.rb
spec/presenters/anonymous_feedback_presenter_spec.rb

Uses the `results_limited` flag from support-api to display more
accurate response counts if the user’s query has been truncated due to
too many results. Also displays useful information on the last
available page.
Before:
After:
Needs pointers from @fofr and Gavan on layout and copy.

UI changes to support feedex result limiting.

---

app/views/support/emergency_contact_details.html.erb

Make it clear that emergency number goes through to the Head of GOV.UK not the operations manager
This is not a change in policy, it's just a clarification of the existing policy.

Clarify emergency phone number destination

---

app/views/support/emergency_contact_details.html.erb

The person answering the phone won't necessarily
be the head of gov.uk.

Change text regarding emergency contact.

---

app/helpers/feedex_helper.rb
app/views/anonymous_feedback/index.html.erb
spec/helpers/feedex_helper_spec.rb

Pages with a path starting with "/done/" have another type of anonymous contact, in addition of comments, called service satisfaction ratings. Due to high volume, the latter are rolled up each evening into service rating aggregates that show the count of each rating. Each service rating aggregate is added as a line in the feedex table, and service satisfaction ratings that have no comments are erased from the table. 
This means that the number of "responses" displayed at the top of the table is misleading for these /done/pages, as they are in fact the number of lines in the table, which for /done/ pages is not relevant. For the feedback of the present day, there is no aggregation, so the number of lines in the table is the number of service satisfaction ratings. For the feedback of …

Remove responses count for done pages

---

LICENCE

Licence taken from https://github.com/alphagov/govuk-rails-app-template/blob/master/templates/LICENCE.erb and marked with the year the project was started (2012).

Add a LICENCE

---

app/controllers/analytics_requests_controller.rb
app/controllers/changes_to_publishing_apps_requests_controller.rb
app/controllers/content_advice_requests_controller.rb
app/controllers/content_change_requests_controller.rb
app/views/analytics_requests/_request_details.html.erb
app/views/changes_to_publishing_apps_requests/_request_details.html.erb
app/views/content_advice_requests/_request_details.html.erb
app/views/content_change_requests/_request_details.html.erb
lib/support/gds/user_facing_components.rb
lib/support/requests/analytics_request.rb
lib/support/requests/changes_to_publishing_apps_request.rb
lib/support/requests/content_advice_request.rb
lib/support/requests/content_change_request.rb
lib/zendesk/ticket/analytics_request_ticket.rb
lib/zendesk/ticket/changes_to_publishing_apps_request_ticket.rb
lib/zendesk/ticket/content_advice_request_ticket.rb
lib/zendesk/ticket/content_change_request_ticket.rb
spec/features/analytics_requests_spec.rb
spec/features/changes_to_publishing_apps_requests_spec.rb
spec/features/content_advice_requests_spec.rb
spec/features/content_change_requests_spec.rb
spec/features/technical_fault_reports_spec.rb
spec/models/support/requests/analytics_request_spec.rb
spec/models/support/requests/changes_to_publishing_apps_request_spec.rb
spec/models/support/requests/content_advice_request_spec.rb
spec/models/support/requests/content_change_request_spec.rb
spec/models/zendesk/ticket/changes_to_publishing_apps_request_ticket.rb
spec/models/zendesk/ticket/content_change_request_ticket_spec.rb

This branch is based on [Support forms text changes](https://github.com/alphagov/support/pull/282) and should not be merged before that branch.
[Trello card](https://trello.com/c/G9xf2aZZ/3-remove-radio-options-on-support-form)
Fewer options (radio buttons) on support request forms.
Some of the forms have had radio buttons removed similar to the following:
The **'Report a technical fault to GDS'** form has had two radio buttons replaced with one:

Radio button changes

---

lib/support/requests/content_advice_request.rb

[Trello card](https://trello.com/c/2PxYo5tt/2-text-changes-to-support-forms)
> I have a very small amendment for one of the descriptions. Can this be amended? For content advice, need to add Request short URLs, topical event pages, groups or manuals. So the entire description would be: Ask for help or advice on any content problems. Request short URLs, topical event pages, groups or manuals.

Update content advice description

---

Gemfile
Gemfile.lock
app/controllers/anonymous_feedback/global_export_requests_controller.rb
app/controllers/authorisation_controller.rb
app/views/anonymous_feedback/explore/new.html.erb
config/initializers/gds-sso.rb
config/routes.rb
lib/support/permissions/ability.rb
spec/controllers/anonymous_feedback/global_export_requests_controller_spec.rb

[Trello card](https://trello.com/c/ptXseJEJ/13-export-global-anonymous-feedback-csv)
This section of the support application (feedex) now allows the
total quantity of requests received each day to be exported as a CSV
file.
Initially, we're protecting this behind a new role (`feedex_exporters`)
so we can control who gets access to the functionality. The main
reasoning here is to allow side-by-side verification of the figures
before rolling it out to wider (perhaps 'single point of contact')
release.

Add the ability to export global feedback

---

app/controllers/analytics_requests_controller.rb
app/controllers/requests_controller.rb
app/views/accounts_permissions_and_training_requests/_request_details.html.erb
app/views/analytics_requests/_request_details.html.erb
app/views/campaign_requests/_request_details.html.erb
app/views/changes_to_publishing_apps_requests/_request_details.html.erb
app/views/content_advice_requests/_request_details.html.erb
app/views/content_change_requests/_request_details.html.erb
app/views/general_requests/_request_details.html.erb
app/views/remove_user_requests/_request_details.html.erb
app/views/requests/new.html.erb
app/views/technical_fault_reports/_request_details.html.erb
app/views/unpublish_content_requests/_request_details.html.erb
lib/support/requests/analytics_request.rb
lib/zendesk/ticket/analytics_request_ticket.rb
spec/features/analytics_requests_spec.rb
spec/models/support/requests/analytics_request_spec.rb

[Trello card](https://trello.com/c/wwElLNWG/21-analytics-support-form-changes)
The Analytics form now has a reduced set of inputs. We validate that the user has filled in at least one of them.
**Before**
**After**

Analytics form changes

---

lib/support/permissions/ability.rb
spec/features/analytics_requests_spec.rb
spec/models/support/requests/permissions_spec.rb

A previous change (from [card](https://trello.com/c/COcqtgck/29-modify-support-permissions)) removed the ability to access this feature from all users and instead only permitted those with 'single point of access' and 'user managers' permissions. This commit reinstates the ability of all users to make analytics requests following feedback from the support team.

Permit all users to make analytics requests

---

config/initializers/gds-sso.rb

As of https://github.com/alphagov/support/pull/296, this app uses env vars. This commit changes the GDS-SSO initialiser to use env vars.

Get GDS-SSO OAuth credentials from env vars

---

Rakefile

CI reporter should only be included in development and test environments.

Guard CI reporter include

---

lib/support/permissions/ability.rb

This commit allows all `support` users to request taxonomy changes as the previous permissions were too restrictive.
Trello: https://trello.com/c/hgqU3MEP/419-allow-feedback-on-taxonomy-from-whitehall

Allow all users to request taxonomy changes

---

lib/support/requests/taxonomy_change_topic_request.rb
lib/support/requests/taxonomy_new_topic_request.rb
spec/features/taxonomy_change_topic_requests_spec.rb
spec/features/taxonomy_new_topic_requests_spec.rb

This commit changes the wording for the taxonomy add/change topic forms to better describe how they should be used.
Trello: https://trello.com/c/RwM6KeSd/508-improve-the-support-form-for-making-add-topic-or-change-topic-requests

Change descriptions for taxonomy forms

---

lib/zendesk/ticket/taxonomy_change_topic_request_ticket.rb
lib/zendesk/ticket/taxonomy_new_topic_request_ticket.rb
spec/features/taxonomy_change_topic_requests_spec.rb
spec/features/taxonomy_new_topic_requests_spec.rb

This commit tweaks the body text of taxonomy request tickets to add the name of the topic as well as rename some fields to be more descriptive.
Trello: https://trello.com/c/RwM6KeSd/508-improve-the-support-form-for-making-add-topic-or-change-topic-requests

Tweak body of taxonomy request tickets

---

lib/support/navigation/section_groups.rb

We're getting a bunch of requests through the two taxonomy forms that aren't about the taxonomy. We think this might be caused by the fact that for non-privileged users (with only `signin` permission) the "Add a topic" form is the first on the page. "Report a technical fault to GDS" used to be first, so maybe they're getting confused about that.
This commit moves the taxonomy forms into a separate group at the bottom. We're hoping this will reduce mis-addressed requests. If it doesn't we'll probably restrict access to the forms to people with `content_requesters` access.
https://trello.com/c/wdIMF2kY

Put taxonomy requests in separate group

---

bin/bundle
bin/rails
bin/rake
bin/setup
config/application.rb
config/environment.rb
config/environments/development.rb
config/environments/production.rb
config/environments/test.rb
config/initializers/assets.rb
config/initializers/cookies_serializer.rb
config/initializers/filter_parameter_logging.rb
config/initializers/inflections.rb
config/initializers/mime_types.rb
config/initializers/secret_token.rb
config/initializers/session_store.rb
config/initializers/wrap_parameters.rb
config/locales/en.yml
config/routes.rb
config/secrets.yml

I ran `rake rails:update` to update existing files and generate new ones. This means our app is now configured like a Rails 4.2 app should be, and this will make it easier to upgrade to Rails 5.
This commit also migrates the app to use `secrets.yml`, and importantly this means it uses the `SECRET_KEY_BASE` env var on deployed environments. The infrastructure work to support this has already been done so we can deploy this without further work. Prior to this we relied on the
`secret_token.rb` initializer being overwritten by our deployment process, but that functionality was stopped in Dec 2016, meaning the app has been insecure since then.

Get application files to Rails 4.2 standard

---

app/views/content_change_requests/_request_details.html.erb
spec/features/content_change_requests_spec.rb

For [Trello card](https://trello.com/c/gdX8tv08/186-rename-field-in-content-request-form)
Follow up to https://github.com/alphagov/support/pull/316

Removes question mark from field label

---

Gemfile
Gemfile.lock
Jenkinsfile
app/controllers/anonymous_feedback_controller.rb
app/helpers/feedex_helper.rb
app/presenters/scope_filters_presenter.rb
app/views/anonymous_feedback/explore/new.html.erb
app/views/anonymous_feedback/index.html.erb
spec/controllers/anonymous_feedback/explore_controller_spec.rb
spec/controllers/anonymous_feedback/export_requests_controller_spec.rb
spec/controllers/anonymous_feedback/global_export_requests_controller_spec.rb
spec/controllers/anonymous_feedback_controller_spec.rb
spec/features/feedex_organisation_summary_spec.rb
spec/features/feedex_spec.rb
spec/features/global_export_request_spec.rb
spec/features/review_anonymous_feedback_spec.rb
spec/features/user_satisfaction_survey_spec.rb
spec/helpers/feedex_helper_spec.rb
spec/presenters/scope_filters_presenter_spec.rb
spec/support/app_actions.rb

For: https://trello.com/c/8wwFr5y0/196-improvements-to-feedex-ui
It's possible to filter feedex by both path and organisation if you manipulate the URL, but there's no UI so it's not obvious.  This PR adds UI elements to make it more obvious and easier to do.
We choose to browse by org, and then decide we want to also filter by a specific path, and finally remove the org constraint.
There's no UI for adding path or removing organisation filters, but we can do it by manually hacking the URL.  The page doesn't tell us we've filtered by multiple things, but the data has been updated accordingly.
UI for path and org filtering is always present on the page, and we've tweaked the help text to make it clear you can use a partial path to filter results.
---
Would particularly appreciate thoughts …

Add ui for filtering by path and org to feedex

---

app/views/support/emergency_contact_details.html.erb

I've simplified the names of the options - it's more obvious which number to call at which time of day now. Also prioritised display of the phone numbers.
@jonsanger has checked the copy.
Before:
After:

Copy changes to emergency contacts page

---

app/workers/zendesk_ticket_worker.rb
spec/workers/zendesk_ticket_worker_spec.rb

A Zendesk ticket is created as long as the requester name is less than 256 characters.
This will remove the Zendesk name to long errors in Sentry.
We (2nd line) started looking at this issue as there were a large number of these errors in Sentry, when we looked at these errors they appears to be spam. We spoke with Liz Lutgendorff and she suggested ignoring any requests there the name was above the 255 limit as these were always spam and not requests from 'real' users.

Fix Zendesk name too long record invalid error

---

app/controllers/anonymous_feedback/export_requests_controller.rb
app/controllers/anonymous_feedback_controller.rb
app/views/anonymous_feedback/index.html.erb
spec/controllers/anonymous_feedback/export_requests_controller_spec.rb
spec/controllers/anonymous_feedback_controller_spec.rb

For: https://trello.com/c/CQBhAvxt/286-fix-feedex-export
When talking to support-api to show results and talking to support-api to generate an export we were treating the params differently.  This meant that you could enter a slash-less path like `done` to get results on the index, but if you tried to export a CSV you would get no results.  This PR fixes that by using the same parameter normalising code in both places.  The API will still return no results for slash-less paths, but the UI will make it hard (impossible?) to send that kind of path to the API.

Normalise path when talking to support api

---

config/initializers/gds_api.rb

https://govuk.zendesk.com/agent/tickets/2540091
Requests to `suppport-api/anonymous_feedback` are
taking about 8 seconds to complete which is timing
out and causing 503 errors in this application.
This sets the default timeout to a maximum of 30
seconds, which is the same as the Nginx timeout.
Really, we should look at fixing the slow queries,
but this solves the immediate problem of users not
being able to use the `/anonymous_feedback` endpoint
of this application.

Increase GdsApi timeout to 30 seconds

---

app/views/content_change_requests/_request_details.html.erb

Added the office hours 'emergency' number, and I removed the stuff at the top. It links out to guidance about how to get the most out of these content requests now.
This is how it should look:

Contact number change

---

app/helpers/feedex_helper.rb
app/views/anonymous_feedback/index.html.erb

For: https://trello.com/c/amR8AiD5/309-feedex-changes-to-workflow
While working on feedex, I requested an export for all the '/done' pages: https://support.integration.publishing.service.gov.uk/anonymous_feedback?path=%2Fdone
This export took 7 hours to perform and resulted in a 1.1 GB file. There was unfortunately no warning that the export would be so big, or that it would require a large amount of time. Had I received a warning, I would have thought twice about asking for such a large file. 
Adds warning when attempting to export a search result.

Improvements to feedex

---

app/models/zendesk/ticket/campaign_request_ticket.rb
app/views/campaign_requests/_request_details.html.erb
spec/features/campaign_requests_spec.rb

This change helps people give better quality responses, improving the quality of thinking that goes in to creating campaign sites.
[Trello Card](https://trello.com/c/zGpgCvS7/32-2-change-text-for-campaign-support-form)

Change text for campaign support form

---

README.md
app/models/support/requests/taxonomy_change_topic_request.rb
app/models/support/requests/taxonomy_new_topic_request.rb
spec/features/taxonomy_change_topic_requests_spec.rb
spec/features/taxonomy_new_topic_requests_spec.rb

The support form's title and description for topic taxonomy alterations
have been changed to better reflect their purpose for collecting data
from publishers.

Update the title and description of topic changes forms

---

config/initializers/gds-sso.rb

In the Rails development environment, this would fail without
Redis. It's not necessary to create the dummy user, so capture the
exception, and just print it.
This should allow asset precompilation to be enabled for the package
in govuk-guix.

Support asset:precompile without Redis

---

app/controllers/content_publisher_feedback_requests_controller.rb
app/models/support/navigation/section_groups.rb
app/models/support/permissions/ability.rb
app/models/support/requests/content_publisher_feedback_request.rb
app/models/zendesk/ticket/content_publisher_feedback_request_ticket.rb
app/views/content_publisher_feedback_requests/_request_details.html.erb
spec/features/content_publisher_feedback_requests_spec.rb
spec/models/support/requests/content_publisher_feedback_request_spec.rb

Putting in a new support feedback page for the content publisher.
These show the changes that were made to the support app to add a new support page.  Wherever possible in the code and the tests, I've borrowed conventions from how the other pages.

Putting in a new support feedback page for the content publisher

---

config/redis.yml
lib/redis_client.rb

The Redis client will use the environment variables by defualt, and
also knows the correct default values, so it's unnecessary to have a
Redis configuration file.
Also, I'm pretty sure nothing is specifying REDIST_PORT...

Remove redundant Redis connection configuration

---

app/controllers/content_data_feedback_controller.rb
app/models/support/navigation/section_groups.rb
app/models/support/permissions/ability.rb
app/models/support/requests/content_data_feedback.rb
app/models/zendesk/ticket/content_data_feedback_ticket.rb
app/views/content_data_feedback/_request_details.html.erb
config/initializers/inflections.rb
spec/features/content_data_feedback_spec.rb
spec/models/support/requests/content_data_feedback_spec.rb
spec/models/zendesk/ticket/content_data_feedback_ticket_spec.rb

https://trello.com/c/Vn3YwWXl/874-3-build-a-new-form-in-the-support-app-for-content-data

Add feedback form for the content data admin

---

Gemfile
Gemfile.lock
app/controllers/anonymous_feedback/export_requests_controller.rb
config/brakeman.ignore
spec/controllers/anonymous_feedback/export_requests_controller_spec.rb

This commit changes the support app to retrieve CSV exports from S3.
Depends on https://github.com/alphagov/support-api/pull/263

Move CSV exports to S3

---

app/models/support/gds/user_facing_components.rb

2nd line have received a number of tickets recently where the requester has selected 'Specialist Publisher' when they are using data.gov.uk.  Adding a new option to reduce the chance of confusion when these tickets are received.

Add data.gov.uk to 'Report a technical fault to GDS'

---

app/controllers/anonymous_feedback/document_types_controller.rb
app/controllers/anonymous_feedback/explore_controller.rb
app/controllers/anonymous_feedback/export_requests_controller.rb
app/controllers/anonymous_feedback/global_export_requests_controller.rb
app/controllers/anonymous_feedback/organisations_controller.rb
app/controllers/anonymous_feedback/problem_reports_controller.rb
app/controllers/anonymous_feedback_controller.rb
app/presenters/scope_filters_presenter.rb

Trello: https://trello.com/c/WR2MNxo6
Related to: 
* https://github.com/alphagov/govuk-puppet/pull/8479
* https://github.com/alphagov/support-api/pull/266
Passes the bearer token needed to authenticate with support-api using signon.

Add bearer tokens for support-api authentication

---

app/controllers/support_controller.rb
app/lib/emergency_contact_details.rb
app/views/support/emergency_contact_details.html.erb
config/initializers/emergency_contact_details.rb
spec/features/emergency_contact_details_spec.rb

We have a request to remove a secondary contact.
This commit allows the emergency-contacts page to 
render when `secondary_contacts` is missing from the JSON.
Trello: https://trello.com/c/6WGS32f2/403-delete-jen-allums-details-from-the-govuk-publishing-support-page

Optional secondary contacts

---

app/views/unpublish_content_requests/_request_details.html.erb
spec/features/unpublish_content_requests_spec.rb

Trello: https://trello.com/c/8F7PqB3E/505-the-unpublishing-support-form-has-been-updated-to-include-instructions-for-content-publisher-as-well-as-whitehall
This is a minor change to make the unpublish content request form mention Content Publisher as well as Whitehall. Since Content Publisher is expected to be used by same users as Content Publisher, and we don't have means for them to unpublish themselves, this is intended to make this form feel less Whitehall specific

Unpublish content mentions Content Publisher

---

Rakefile

The lint task is not run by default.
This means you don't find out about linting errors until CI.
We want to `fail fast` so adding linting as part of the default
rake task.

Add linting to the default rake task

---

app/controllers/eu_exit_business_readiness_requests_controller.rb
app/models/support/requests/eu_exit_business_readiness_request.rb
app/models/zendesk/ticket/eu_exit_business_readiness_ticket.rb
app/views/eu_exit_business_readiness_requests/_request_details.html.erb
spec/features/eu_exit_business_readiness_request_spec.rb

When creating the Zendesk ticket to add content to the business
finder. We want to be able to specify if the content should
be pinned.
This PR allows the user to specify this in the support form.
The resulting ZenDesk ticket will have this information.
Trello: https://trello.com/c/rEBhX1IB/190-add-a-pinning-option-to-the-business-readiness-support-form

Add pinning to business readiness form

---

.rspec
app/controllers/anonymous_feedback_controller.rb
app/models/support.rb
app/models/support/requests.rb
app/models/support/requests/anonymous.rb
app/models/support/requests/anonymous/explore.rb
app/models/support/requests/anonymous/paths.rb
app/views/anonymous_feedback/index.html.erb
config/routes.rb
spec/controllers/anonymous_feedback/explore_controller_spec.rb
spec/controllers/anonymous_feedback_controller_spec.rb
spec/models/support/requests/anonymous/explore_by_multiple_paths_spec.rb
spec/models/support/requests/anonymous/paths.rb
spec/models/user_spec.rb
spec/support/redis.rb

This stores the paths for an anonymous feedback request in Redis, allowing the user to input many more paths than is currently possible. Currently, the paths are stored in the query parameter for the GET request, and this limits the length of the string. An alternative would be to switch to using POST to execute the query, but this makes it impossible to share the URL. Instead, a solution that involves using POST to submit the form, which then saves the paths in an object in Redis and then includes a reference to the object in the resulting GET request URL was chosen.
[Trello Card](https://trello.com/c/EGvu5WoK/757-make-feedex-able-to-return-results-for-larger-sets-of-urls-by-changing-request-from-get-to-post)

Store anonymous feedback paths in Redis

---

app/controllers/anonymous_feedback_controller.rb
spec/controllers/anonymous_feedback_controller_spec.rb

This fixed a bug that was introduced in #606. In that implementation, the `params` variable gets modified with the expanded paths. However this means the pagination, which is automatically generated based on the params, links to the expanded paths rather than the shorted params. Therefore users wouldn't be able to visit second pages when uploading lots of URLs because the same problem as before would occur.
[Trello Card](https://trello.com/c/zfFWlA9r/965-feedex-error-when-viewing-results)

Don't expand params when loading paths

---

app/controllers/eu_exit_business_readiness_requests_controller.rb
app/lib/services.rb
app/models/support/requests/eu_exit_business_readiness_request.rb
app/models/zendesk/ticket/eu_exit_business_readiness_ticket.rb
app/presenters/facets/base_presenter.rb
app/presenters/facets/facet_group_presenter.rb
app/presenters/facets/facet_presenter.rb
app/presenters/facets/facet_value_presenter.rb
app/services/remote_facet_group_service.rb
app/views/eu_exit_business_readiness_requests/_request_details.html.erb
spec/features/eu_exit_business_readiness_request_spec.rb
spec/models/support/requests/eu_exit_business_readiness_request_spec.rb
spec/presenters/facets/facet_group_presenter_spec.rb
spec/presenters/facets/facet_presenter_spec.rb
spec/services/remote_facet_group_service_spec.rb

Facet values are currently hardcoded in the EU Exit business readiness request from and therefore have to be manually changed when the facet value is updated in the finder.
This populates a support form with values obtained from the Publishing API.
Dependent on https://github.com/alphagov/govuk-puppet/pull/9080 
Test by checking if options for _Is the content about selling goods in the UK, importing or doing business abroad?_ question are in the ground form (eg. _sell_, not _selling_)
[Trello card](https://trello.com/c/HPOb08N2/69-change-business-activity-title-to-organisation-activity-in-zendesk-ticket-generated-by-support-form)

Update business finder request to use facet values from Publishing API

---

app/controllers/eu_exit_business_readiness_requests_controller.rb
app/models/support/requests/eu_exit_business_readiness_request.rb
app/models/zendesk/ticket/eu_exit_business_readiness_ticket.rb
app/views/eu_exit_business_readiness_requests/_request_details.html.erb
spec/features/eu_exit_business_readiness_request_spec.rb

Trello: https://trello.com/c/VTQHxlfH
Related to:
* https://github.com/alphagov/finder-frontend/pull/1202
* https://github.com/alphagov/content-tagger/pull/940
Content can no longer be pinned to the Brexit business finder, so the option needs to
be removed from the support form

Remove option to pin content from Brexit form

---

app/models/support/requests/eu_exit_business_readiness_request.rb
app/models/zendesk/ticket/eu_exit_business_readiness_ticket.rb
app/views/eu_exit_business_readiness_requests/_request_details.html.erb
spec/features/eu_exit_business_readiness_request_spec.rb

Trello: https://trello.com/c/VTQHxlfH
Related to: PR #636 
The rules for tagging to the Brexit business finder have changed. The support app is being updated to reflect those changes.
The requested changes are here: https://docs.google.com/document/d/1ZGrHqLb5vitCcc3I7Z5VzZFrcjm4AhLLXLrI-LM_Ubs/edit#
Pinning was removed in PR #636
The sector names (except for the Employing people question) are populated from the facet-group in publishing-api.

Update guidance on Brexit business form

---

app/controllers/brexit_checker_requests_controller.rb
app/models/support/navigation/section_groups.rb
app/models/support/permissions/ability.rb
app/models/support/requests/brexit_checker_request.rb
app/models/zendesk/ticket/brexit_checker_ticket.rb
app/views/brexit_checker_requests/_request_details.html.erb
spec/features/brexit_checker_request_spec.rb

For https://trello.com/c/bgtCMkNP/243-zendesk-content-change-request-form
This creates a request form for departments to request a change to an existing action or creating a new action for the Get Ready For Brexit Checker.  Once submitted, a request is made to the Zendesk API to create a ticket.

Add brexit checker support form

---

config/environments/development.rb

Related: https://github.com/alphagov/link-checker-api/pull/284
Custom alias domains such as http://support.dev.gov.uk are not working
on any apps running Rails 6, due to the addition of "Host Authorisation"
middleware.
Without this fix you get this error when trying to access the support
app in browser.
> Blocked host: support.dev.gov.uk
> To allow requests to support.dev.gov.uk, add the following to your environment configuration:
> config.hosts << support.dev.gov.uk

Fix support for local docker dev environment

---

app/models/support/requests/accounts_permissions_and_training_request.rb
app/views/accounts_permissions_and_training_requests/_request_details.html.erb
app/views/accounts_permissions_and_training_requests/_user_needs.html.erb
spec/features/accounts_permissions_and_training_requests_spec.rb

Trello: https://trello.com/c/cipBS5VE/1454-2-small-changes-to-a-support-form
Just some quick changes to remove mentions of unsuspending accounts.

Changes to Accounts, Permissions and Training form

---

app/views/support/emergency_contact_details.html.erb

The whitespace created by two `<p>` tags is inconsistent with the rest
of the page. Remove it and replace it with a `<br>` instead.

Remove whitespace between two lines of emergency contact

---

app/models/support/gds/campaign.rb
app/views/campaign_requests/_request_details.html.erb
spec/features/campaign_requests_spec.rb
spec/models/support/gds/campaign_spec.rb

This PR updates the validations on the campaign request form.
Previously campaign site development start dates were validated to be `on_or_after` the campaign start date. This corrects this validation to ensure that site development must begin `on_or_before` the campaign start date.
The cost of campaign numericality validation has been removed to allow users to use text as well as numbers.
Additionally some description contents have been updated.
**Before**
Incorrect validation: build date AFTER start date
Outdated validation: text disallowed
**After**
Correct validation: Build date must be on or BEFORE start date
Successful submission with text and numbers, and build date
[Trello](https://trello.com/c/NvpqqaTw/1690-3-changes-to-fields-in-apply-for-a-campaign-form)

Correct campaign request validations

---

spec/features/campaign_requests_spec.rb
spec/features/content_advice_requests_spec.rb
spec/features/content_change_requests_spec.rb
spec/features/remove_user_requests_spec.rb

The year is now 2020, and the steady passage of time has invalidated these once passing tests.

Update hard coded test dates to always be in the future

---

spec/features/user_satisfaction_survey_spec.rb

Timecop freezes time to 2013, which causes another subsequent test
(spec/features/campaign_requests_spec.rb:16), which uses Time.current,
to fail.
https://ci.integration.publishing.service.gov.uk/job/support/job/update-brexit-checker/8/console
Resetting the time after this test has run fixes the issue.

Fix flaky test caused by Timecop and Time.current

---

app/controllers/anonymous_feedback/export_requests_controller.rb
app/views/anonymous_feedback/index.html.erb
spec/controllers/anonymous_feedback/export_requests_controller_spec.rb

Recently we refactored feedback CSV exports so that post requests are
sent with a Redis `path_set_id` rather than a large list of URLs.
https://github.com/alphagov/support/pull/672
Whilst it no longer possible with the Support app itself to access the `anonymous_feedback` path without first generating a `path_set_id`, direct links do exist within the GOV.UK Chrome extension and the Content-Data app. This causes the ExportRequestsController to send through a request to the Support-API with an invalid `path_prefixes: scope_filters.paths_for_api`
This PR ensures that when directly accessing this controller with a string URL `path` or `paths` param, clicking the `Export as CSV` button will cause the ExportRequestsController to create a valid Redis `path_set_id` if one is not set. This is in …

Ensure Feedback Export requests have a valid `path_prefixes` param

---

.rubocop.yml
Rakefile
lib/tasks/lint.rake

- This is a prerequisite for being able to move more of our apps to
GitHub Actions. We want one single step bundle exec rake that runs
everything. This ensures parity between local dev and what CI runs
(something that we don't always have now).
- Also tidy up the contents of `.rubocop.yml` - the disabled cops here
are all disabled in the gem configs these days.
https://trello.com/c/5Gob6WUL/147-for-everyone-ensure-that-rubocop-runs-as-part-of-bundle-exec-rake-as-one-of-the-default-tasks

Run RuboCop as part of `bundle exec rake` defaults

---

app/models/zendesk/ticket/campaign_request_ticket.rb
app/views/campaign_requests/_request_details.html.erb
spec/features/campaign_requests_spec.rb

This is a content change to update the new campaign request form
We are changing the old content:
"Name of the head of digital who signed off the campaign website application"
To:
"Name of the Head of Digital Communications who signed off the campaign website application"

Update content on request new campaign page

---

.gitignore
config/initializers/gds_sso.rb

https://trello.com/c/epNWudCR/176-write-an-rfc-for-continuous-deployment-and-seek-review
This was made redundant in [1].
[1]: https://github.com/alphagov/gds-sso/pull/241

Remove redundant GDS SSO initializer

---

app/models/support/gds/campaign.rb
app/models/zendesk/ticket/campaign_request_ticket.rb
app/views/campaign_requests/_request_details.html.erb
spec/features/campaign_requests_spec.rb
spec/models/support/gds/campaign_spec.rb

We want to update the campaigns application form in the Support app to reflect changes in the way campaigns are applied for.
To this end we want to remove the existing text from the current form 
• A campaign platform site is a one page website on campaign.gov.uk
• Microsite websites are not built on GOV.UK and may or may not have a gov.uk url. Microsite websites fall under Cabinet 
Office digital service expenditure therefore GDS spend approval must be sought following approval from GCS to 
develop a campaign microsite.*
We also want to remove any reference to microsites. 
**BEFORE**
**AFTER**
[Trello](https://trello.com/c/C7maXqA2/324-non-covid-update-campaigns-application-form-in-support-app)
⚠️ This repo is Continuously Deployed: make sure you [follow the …

Update campaign form

---

app/views/support/emergency_contact_details.html.erb
spec/features/emergency_contact_details_spec.rb

This pull request makes content and structural changes to the emergency contact details page.

Update emergency contact details page content

---

app/models/support/navigation/section_groups.rb
app/models/support/requests/taxonomy_change_topic_request.rb
app/models/support/requests/taxonomy_new_topic_request.rb
app/views/taxonomy_new_topic_requests/_request_details.html.erb
spec/features/taxonomy_change_topic_requests_spec.rb
spec/features/taxonomy_new_topic_requests_spec.rb

As part of the work to align terminology relating to topics, taxonomy and tagging in the publishing apps in June 2022, the Navigation & Presentation team updated microcopy in Whitehall, Publisher, Collections Publisher and Content Tagger.
This final task is to make relevant changes in the GOV.UK Support app.
[See the docs for the requests and before/after screenshots](https://docs.google.com/document/d/1clABq9P3M0FwcVElflKnXK3hCr4OXKkLcqIBVNTmCfY/edit#heading=h.ydtlgrzhd0c)
[Trello](https://trello.com/c/ERXoBxRL/1311-govuk-support-app-update-copy-based-on-jenns-doc-m)

Update copy for topic taxonomy requests

---

app/controllers/campaign_requests_controller.rb
app/models/support/gds/campaign.rb
app/models/zendesk/ticket/campaign_request_ticket.rb
app/views/campaign_requests/_request_details.html.erb
spec/features/campaign_requests_spec.rb
spec/models/support/gds/campaign_spec.rb

The advice in the campaigns section of the content design manual is being updated due to a change in processes.
https://trello.com/c/8cSxyJH2/2932-3-changes-to-request-a-new-campaign-form
**BEFORE**
**AFTER**

Update request new campaign page

---

app/assets/stylesheets/application.scss
app/views/anonymous_feedback/_anonymous-contact.html.erb

Add class `text-break` to `application.css` to cause text wrapped to break words as it is defined in later versions of bootstrap.
Use this class in the feedback explorer table.
Users including URLs or horizontal rules in their feedback would back the formatting of the page as the column width with increase to cover the full table

Add text-break class to feedback explorer

---

Gemfile.lock
app/models/support/requests/anonymous/paths.rb
app/models/user.rb
lib/govuk_redis_client.rb
lib/volatile_lock.rb
spec/models/user_spec.rb
spec/models/volatile_lock_spec.rb
spec/support/redis.rb

Replaces #1017, which is a bit fiddly to unpick (conflicts). Since that PR was raised, [govuk_sidekiq has been bumped](https://github.com/alphagov/support/pull/1069), so we can drop 8cb0f4187f89ea09d544019b3decd08fc174aec2 and 9005b531b6c4db0932c6c827ad74d64638b24cc2.
-----

Bump redis from 4.5.1 to 5.0.5 (manually)

---

app/controllers/authorisation_controller.rb
app/controllers/support_controller.rb
app/lib/emergency_contact_details.rb
app/views/content_change_requests/_request_details.html.erb

We should be using the same approach as the 'emergency contact
details' page: https://github.com/alphagov/support/blob/2780b2e30306ab21647abd4db4b7d6809f81144a/app/views/support/emergency_contact_details.html.erb#L54
The phone number values are set here:
https://github.com/alphagov/govuk-secrets/pull/1443
I've had to move the `emergency_contact_details` method definition
into `AuthorisationController` as we now need to make it
available to `RequestsController`, which inherits from it.
`SupportController` (where I've taken the method definition from)
also inherits from `AuthorisationController`, so it should
continue to work for both scenarios.
⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#m …

Update contact details

---

app/views/support/emergency_contact_details.html.erb

The team have agreed that there is no genuine user need for including this here and would like to minimise the risk of this email address being used incorrectly.
https://govuk.zendesk.com/agent/tickets/5181812

Remove GOV.UK Verify non-urgent support and feedback contacts

---

Gemfile.lock

Fixes this error on `bundle install`:
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name =>
spell_checker)' has been deprecated. Please call
`DidYouMean.correct_error(error_name, spell_checker)' instead.

Update bundler to fix warning about deprecated method.

---

.dockerignore
Jenkinsfile
Procfile
README.md
config/unicorn.rb
lib/tasks/lint.rake

- Remove Jenkinsfile and Procfile; we no longer build/test on Jenkins and we no longer run on Foreman (or Heroku, or anything else that uses Procfile).
- Update the README to remove references to govuk-puppet etc.
- Fix the rake task for running the linters.
- Remove the Unicorn config so that we're ready for when Unicorn is removed in a future govuk_app_config release.

Post-replatforming cleanup.

---

yarn.lock

to fix security vulnerability: Regular Expression Denial of Service in hosted-git-info 
The npm package hosted-git-info before 3.0.8 are vulnerable to Regular Expression Denial of Service (ReDoS) via regular expression shortcutMatch in the fromUrl function in index.js. The affected regular expression exhibits polynomial worst-case time complexity.

Update dependencies with `npm audit fix`

---

app/lib/emergency_contact_details.rb
config/environments/development.rb
config/environments/test.rb
spec/lib/emergency_contact_details_spec.rb

The `EmergencyContactDetails` class relies on a `EMERGENCY_CONTACT_DETAILS` ENV variable to define sensitive information such as phone numbers and email addresses, which we then display in the Support app.
If the ENV variable is missing, then it falls back to the nonsense data in `config/emergency_contact_details.json`, potentially displaying incorrect information to publishers. It would be better for the application to crash.
The fallback behaviour has instead been moved to
`config/environments`, in `development.rb` and `test.rb` only. This is so that the app can be started up without having to define the ENV var (`development.rb`) and so that all of the unrelated tests continue to pass (`test.rb`).
⚠️ This repo is Continuously Deployed: make sure you [follow the …

Don't fall back to fixture data in production

---

app/models/support/requests/time_constraint.rb
app/models/zendesk/zendesk_tickets.rb
spec/features/content_change_requests_spec.rb

Part of the work of adding [Zendesk mappings](https://trello.com/c/9j3DslWM/3176-apply-zendesk-mapping-to-the-content-requests-form-5) but it can be separated from the new feature PR.
See commit messages for details.
---

Content change request form tidy up

---

app/models/zendesk/ticket/content_change_request_ticket.rb
spec/features/content_change_requests_spec.rb
spec/models/zendesk/ticket/content_change_request_ticket_spec.rb

- **Remove "Content change request" suffix from the Zendesk ticket subject** 
These tickets default to "Content Request" form so there's no need to add an extra
suffix to the subject.
- **Temporarily add content request fields into the ticket body** 
There is an issue with Zapier integration the content teams use to create
Trello cards from Zendesk tickets.  Deadlines/not-before dates aren’t pulling
through on cards because this data is now in different fields. This was
anticipated however colleagues with with login details to the Zapier account
are not available today to make a change.  We will temporarily add this
information to the ticket body so it's copied over to Trello with Zapier.
Once Zapier is updated we can revert this change. …

Update Content change request ticket subject and temporarily add fields into body

---

Gemfile
Gemfile.lock

This gem has been pretty much abandoned and we need to do the work to ultimately replace it with a component available in the design system, however this is a quick fix for the alerts we've been getting.

Update dependency to solve alerts

---

app/controllers/campaign_requests_controller.rb
app/models/support/gds/campaign.rb
app/models/zendesk/ticket/campaign_request_ticket.rb
app/views/campaign_requests/_request_details.html.erb
spec/features/campaign_requests_spec.rb
spec/models/support/gds/campaign_spec.rb

Add HMG code and strategic planning code fields to the request a new campaign form.
https://trello.com/c/NoFOCDwj/3320-add-fields-to-the-request-a-new-campaign-form-in-support-app-2

Add fields to the 'Request a new campaign' form

---

app/models/support/requests/requester.rb
spec/models/support/requests/requester_spec.rb

Some email addresses contain an apostrophe in the person's name before the `@` symbol, but we are currently disallowing them.
This adds that character into the validation for email addresses.
Resolved https://govuk.zendesk.com/agent/tickets/5548904.

Permit apostrophe in email address

---

app/controllers/create_new_user_requests_controller.rb
app/views/create_new_user_requests/_requested_user_details.html.erb
spec/controllers/create_new_user_requests_controller_spec.rb

This fixes a couple of bugs:
* A `NoMethodError` was being raised for any server-side validation error for this form
* The selected organisation was not being retained after a server-side validation error
Luckily both of these were masked from most users by the client-side validation and this may explain why we haven't seen any `NoMethodError` exceptions in the wild.

Fix validation-related bugs for organisation field in "Create new user" request form

---

Gemfile.lock

c.f. https://github.com/alphagov/whitehall/pull/6934
We ran the following commands:
bundle lock --add-platform ruby
bundle lock --add-platform aarch64-linux
bundle lock --add-platform arm64-darwin
bundle lock --add-platform x86_64-linux
We've been seeing discrepancies in the `Gemfile.lock` when adding new gems with native extensions to this app whereby the new gem only gets added for the current bundler platform. We're hoping that making this change which has been made in a bunch of other GOV.UK apps will avoid that happening in future PRs.

Add platforms to Gemfile.lock

---

app/controllers/report_an_issue_with_govuk_search_results_requests_controller.rb
app/models/support/navigation/section_groups.rb
app/models/support/permissions/ability.rb
app/models/support/requests/report_an_issue_with_govuk_search_results_request.rb
app/models/zendesk/ticket/report_an_issue_with_govuk_search_results_request_ticket.rb
app/views/report_an_issue_with_govuk_search_results_requests/_request_details.html.erb
spec/controllers/report_an_issue_with_govuk_search_results_requests_controller_spec.rb
spec/features/report_an_issue_with_govuk_search_results_spec.rb
spec/models/support/permissions/ability_spec.rb
spec/models/support/requests/report_an_issue_with_govuk_search_results_request_spec.rb
spec/models/zendesk/ticket/report_an_issue_with_govuk_search_results_request_ticket_spec.rb

https://trello.com/c/odKZPy7o
GOV.UK are trialling a new search engine. This new form allows people to report problems they encounter with this new search engine.

Add form for people to report problems with new GOV.UK search

---

app/controllers/technical_fault_reports_controller.rb
app/models/support/gds/user_facing_component.rb
app/models/support/gds/user_facing_components.rb
app/models/support/gds/with_request_context.rb
app/models/support/requests/change_existing_user_request.rb
app/models/support/requests/create_new_user_request.rb
app/models/support/requests/technical_fault_report.rb
app/models/zendesk/ticket/change_existing_user_request_ticket.rb
app/models/zendesk/ticket/create_new_user_request_ticket.rb
app/models/zendesk/ticket/technical_fault_report_ticket.rb
app/models/zendesk/ticket/unpublish_content_request_ticket.rb
app/models/zendesk/zendesk_ticket.rb
spec/features/technical_fault_reports_spec.rb
spec/features/unpublish_content_requests_spec.rb
spec/models/support/gds/user_facing_component_spec.rb
spec/models/support/gds/with_request_context_spec.rb
spec/models/support/requests/technical_fault_report_spec.rb
spec/models/zendesk/ticket/technical_fault_report_ticket_spec.rb

This PR fixes several problems:
1. Whitehall being referred to as "Inside Government Publisher" (nobody calls it that anymore). Now fixed to Whitehall.
2. Removes unused `formatted_request_context` method in `WithRequestContext` module.
3. Lots of special cases around adding an "inside_government" tag, which is no longer used in any routing in Zendesk: See [screenshot of Zendesk 'Triggers' search](https://github.com/alphagov/support/assets/5111927/27309a74-998a-4b87-81b6-0b4f0e019850)
What _is_ used is the `fault_with_inside_government_publisher` tag on the [Initial Routing: Gov't Form publisher tech fault requests to 2nd Line--GOV.UK Alerts and Issues](https://govuk.zendesk.com/admin/objects-rules/rules/triggers/35985647) (to route to Technical 2nd Line). This will now be changed to …

Remove "inside government" logic

---

app/models/support/requests/technical_fault_report.rb
app/models/zendesk/ticket/technical_fault_report_ticket.rb
spec/features/technical_fault_reports_spec.rb
spec/models/support/requests/technical_fault_report_spec.rb

Before: "Technical fault report"
After:" Technical fault with {APP_NAME}"
---

Make technical fault report Zendesk ticket subjects more useful

---

app/models/support/requests/technical_fault_report.rb

Also adds an inline comment giving a strong hint to the developer to check Zendesk when making changes to this config.
See commits for details.
---

Update list of applications for the Technical Fault Report form

---

app/controllers/create_new_user_requests_controller.rb
app/models/support/requests/create_new_user_request.rb
app/models/zendesk/ticket/create_new_user_request_ticket.rb
app/views/create_new_user_requests/_request_details.html.erb
config/application.rb
config/locales/en.yml
spec/controllers/create_new_user_requests_controller_spec.rb
spec/features/create_new_user_requests_spec.rb
spec/models/support/requests/create_new_user_request_spec.rb

https://trello.com/c/2B5qTHlZ
We are going to add additional questions so that the user can specify whether
they want to list any additional publishing applications.
Therefore, this label is updated to be less generic.
As the "additional comments" question is quite generic, 2nd line content is
having to reply to users to specify whether the new user need access to
Whitehall publisher.
Add a new question that specifically asks whether the user needs access to
Whitehall publisher.
As the "additional comments" question is quite generic, 2nd line content is
having to reply to users to specify whether the new user need access to
applications other than Whitehall publisher.
Add a new question that specifically asks whether the user needs access to apps
other than Whitehall publisher.
Additional …

Create new user form improvements

---

app/models/support/requests/technical_fault_report.rb
spec/models/support/requests/technical_fault_report_spec.rb

On @nicholsj' suggestion:
- We should have a "Search" option for general tech support issues (as opposed to the existing https://support.publishing.service.gov.uk/report_an_issue_with_govuk_search_results_request/new form, which is for reporting search results themselves)
- We should have an option for "Feedback explorer" (it's part of the Support app, but users don't necessarily know that, and it may well move into Content Data in future)
- We can make it clearer that "Do not know" is also for times where the user _does_ know the area, but it doesn't fit into any of the existing options.
NB, I'll get User Support to make sure the `fault_with_feedback_explorer` tag routes to [GOV.UK Platform Support](https://govuk.zendesk.com/agent/filters/12863141605916).
⚠️ This repo is Continuously …

Update technical fault options as per March 2024 review

---

.govuk_dependabot_merger.yml

Add govuk_publishing_components to auto-merge list

---

app/presenters/scope_filters_presenter.rb

Escaped `.` regular expression is more specific and restrictive in its matching of the domain name "gov.uk" by ensuring that the dot character is exactly matched, whereas the old regular expression allows for any character to be present in place of the dot. 
This means it will only match "gov.uk" and won't match variations like "govXuk" or "gov1uk".
Trello: https://trello.com/c/tiWPB7lJ/3474-review-code-scanning-alerts-for-our-repos

Improve URL regex match

---

app/views/layouts/application.html.erb
app/views/layouts/design_system.html.erb

This allows us to implement basic GA4 tracking on all pages of the app. It is configured using the following environment variables:
- GOOGLE_TAG_MANAGER_ID
- GOOGLE_TAG_MANAGER_AUTH (integration only)
- GOOGLE_TAG_MANAGER_PREVIEW (integration only)
If only the `GOOGLE_TAG_MANAGER_ID` is set then the default environment of the GTM container will be used.
If `GOOGLE_TAG_MANAGER_AUTH` and `GOOGLE_TAG_MANAGER_PREVIEW` are set then the specified GTM container environment will be used - specifically for testing the configuration in Integration before rolling out to Production.
This has been successfully tested in Integration using [the test environment](https://tagmanager.google.com/?pli=1#/container/accounts/6005964263/containers/168629509/workspaces/6/variables) in Google Tag Manager.
Related …

Setup Google Tag Manager

---

app/controllers/application_controller.rb

If the security token doesn't match what was expected, an exception will be thrown.
Ref: https://guides.rubyonrails.org/security.html#required-security-token
The Ruby guide above gives a solution to implement better CSRF protection.
Trello: https://trello.com/c/tiWPB7lJ/3474-review-code-scanning-alerts-for-our-repos

Update CSRF protection

---

.github/workflows/deploy.yml
Dockerfile

This swaps out the GitHub Workflow to use the multi-arch build flow so we can start baking ARM images to test on Graviton in Integration.
Also poking @AgaDufrat on PSR team for visibility!

Swap to the multi-arch Docker build for ARM

---

app/helpers/referrer_helper.rb

Caught in CodeQL alert
Sanitising untrusted input with regular expressions is a common technique. However, it is error-prone to match untrusted input against regular expressions without anchors such as \A or \z. Malicious input can bypass such security checks by embedding one of the allowed patterns in an unexpected location.
Trello: https://trello.com/c/tiWPB7lJ/3474-review-code-scanning-alerts-for-our-repos

Sanitising input

---

app/controllers/anonymous_feedback/document_types_controller.rb
app/controllers/anonymous_feedback/explore_controller.rb
app/controllers/anonymous_feedback/export_requests_controller.rb
app/controllers/anonymous_feedback/global_export_requests_controller.rb
app/controllers/anonymous_feedback/organisations_controller.rb
app/controllers/anonymous_feedback/problem_reports_controller.rb
app/controllers/anonymous_feedback_controller.rb
app/controllers/create_new_user_requests_controller.rb
app/lib/services.rb
app/presenters/scope_filters_presenter.rb

This follows pattern of other GOV.UK apps. It removes duplication and the service won't need to be instantiated in each controller.
SUPORT_API_BEARER_TOKEN is defined in all environments:
- https://github.com/alphagov/govuk-helm-charts/blob/e060791/charts/app-config/values-integration.yaml#L2899-L2903
- https://github.com/alphagov/govuk-helm-charts/blob/e060791/charts/app-config/values-staging.yaml#L2801-L2805
- https://github.com/alphagov/govuk-helm-charts/blob/e060791/charts/app-config/values-production.yaml#L2913-L2917
[Trello](https://trello.com/c/lkOEEOBG/3551-use-support-api-to-raise-tickets-from-support-5)
---
⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-your-own-pull-request) …

Refactor how we call Support API

---

app/models/zendesk/zendesk_tickets.rb
app/workers/zendesk_ticket_worker.rb
spec/controllers/change_existing_user_requests_controller_spec.rb
spec/controllers/create_new_user_requests_controller_spec.rb
spec/controllers/general_requests_controller_spec.rb
spec/controllers/requests_controller_spec.rb
spec/features/analytics_requests_spec.rb
spec/features/campaign_requests_spec.rb
spec/features/change_existing_user_requests_spec.rb
spec/features/changes_to_publishing_apps_requests_spec.rb
spec/features/content_advice_requests_spec.rb
spec/features/content_change_requests_spec.rb
spec/features/content_data_feedback_spec.rb
spec/features/create_new_user_requests_spec.rb
spec/features/general_requests_spec.rb
spec/features/live_campaign_requests_spec.rb
spec/features/remove_user_requests_spec.rb
spec/features/report_an_issue_with_govuk_search_results_spec.rb
spec/features/taxonomy_change_topic_requests_spec.rb
spec/features/taxonomy_new_topic_requests_spec.rb
spec/features/technical_fault_reports_spec.rb
spec/features/unpublish_content_requests_spec.rb
spec/models/zendesk/zendesk_tickets_spec.rb
spec/support/gds_zendesk_helpers.rb
spec/workers/zendesk_ticket_worker_spec.rb

Switches to using the [/support-tickets Support API endpoint via GDS API Adapters](https://github.com/alphagov/gds-api-adapters/blob/9b03c6d5e8ec03ce86d79fdc1ed0efdd0b474095/lib/gds_api/support_api.rb#L25).
It also removes GovukStatsd, which is deprecated. Raising appropriate errors that will appear in Sentry will still allow us to track the issues without the need for dashboards.
It uses Sidekiq configuration to handle exceptions appropriately.
gds_zendesk is deprecated and will be archived.
---

Use Support API to raise Zendesk tickets

---

app/controllers/create_new_user_requests_controller.rb
spec/controllers/change_existing_user_requests_controller_spec.rb
spec/controllers/create_new_user_requests_controller_spec.rb
spec/features/change_existing_user_requests_spec.rb
spec/features/create_new_user_requests_spec.rb

This functionality was originally introduced 12 years ago, with no explanation as to why it was needed: https://github.com/alphagov/support/pull/22
It removes the complexity from Support app and allows us to retrie `gds_zendesk` gem, without the need to create another API endpoint.
It seems unnecessary to create Zendesk account for users who may not need to ever raise Zendesk tickets.  When a Zendesk ticket is received, a Zendesk account is automatically created for a user.
At present only name, email and organisation are set or updated. Having this information in Zendesk add little value, as organisation can be derived from email address. 
The 'Change existing user request' doesn't update Zendesk accounts.
All those properties can be updated by the users themselves if necessary (e.g. …

Don't create Zendesk account for new user requests

---

app/models/support/requests/technical_fault_report.rb
spec/features/technical_fault_reports_spec.rb

There was a missing full-stop from the end of the line and in `e.g.`.

Add missing full stops to technical fault report description.

---

app/views/change_existing_user_requests/_request_details.html.erb

Adding an alert to the form, advising users trying to use this form
of circumstances when they do not need to raise a request.
As per Zendesk ticket: [https://govuk.zendesk.com/agent/tickets/5908958](url)
Closes https://github.com/alphagov/support/issues/1463

Adding alert to Change Existing User Account form

---

app/views/campaign_requests/_request_details.html.erb
app/views/content_advice_requests/_request_details.html.erb
app/views/remove_user_requests/_request_details.html.erb
app/views/support/_time_constraint.html.erb

Adds:
- missing hint text for date input fields
- fieldset and label HTML tags
- missing `<div class="govuk-form-group">` and `<div class="govuk-date-input”>`
- switches spans to divs which ensures correct margins without need for line breaks
- inputmode="numeric" 
Also corrects indentation.
As per https://design-system.service.gov.uk/patterns/dates/
<kbd><img width="411" alt="Screenshot 2024-09-20 at 13 51 40" src="https://github.com/user-attachments/assets/9b585ffe-fdd4-4ae5-b571-e8a434843014"></kbd>
---
Follow [these steps](https://guides.rubyonrails.org/upgrading_ruby_on_rails.html) if you are doing a Rails …

Update date input components

---

app/models/support/requests/technical_fault_report.rb

Content Publisher is a deprecated app, and had just 9-17 monthly users in the last quarter.
https://docs.google.com/document/d/1qcnGDzw5PKKg97c3ivDpBtmbbutsUcIfk5GZxqLqFjg/edit?tab=t.0#heading=h.sll6kqtr8gmz
Of the 9 technical fault reports associated with "Content Publisher" raised since August, just 1 has actually been to do with Content Publisher. The other 8 were all Whitehall requests.
Removing this option from the form should make it clearer to users that "Whitehall" or "GOV.UK: content" is the option they need, and should reduce the number of misleadingly labelled Zendesk tickets for our support queue.
If users have a genuine issue with Content Publisher itself, they can choose the "Other / do not know" option.
⚠️ This repo is Continuously Deployed: make sure you [follow the …

Remove "Content Publisher" as an option on Technical Fault Report

---

app/views/content_change_requests/_request_details.html.erb
app/views/support/emergency_contact_details.html.erb
config/emergency_contact_details.json

🛑  DO NOT MERGE until we are given the go-ahead from Keith or John-Paul.
The office hours content emergency phone is being replaced by a group email address. 
Closes https://github.com/alphagov/support/issues/1614
Integration URL: https://support.integration.publishing.service.gov.uk/content_change_request/new
| Before    | After |
| -------- | ------- |
|  n/a due to sensitive content | <img width="561" alt="Screenshot 2025-02-12 at 14 55 29" src="https://github.com/user-attachments/assets/8c15e204-a053-4fbc-8b7f-094b0c646a14" /> |
Screenshots not available due to sensitive content. 
Visit integration URL for review: https://support.integration.publishing.service.gov.uk/emergency-contact-details
- check if secrets include the new value
- visit …

Change content emergency contact

---

app/controllers/create_new_user_requests_controller.rb
app/models/support/requests/create_new_user_request.rb
app/models/zendesk/ticket/create_new_user_request_ticket.rb
app/views/create_new_user_requests/_request_details.html.erb
config/locales/en.yml
config/zendesk/custom_fields_data.yml
spec/controllers/create_new_user_requests_controller_spec.rb
spec/features/create_new_user_requests_spec.rb
spec/models/support/requests/create_new_user_request_spec.rb
spec/models/zendesk/ticket/create_new_user_request_ticket_spec.rb

[Trello](https://trello.com/c/IN20Asaz/1634-updates-to-the-create-new-user-support-form)
This updates the create new user request form per a content team request. The main changes are two new questions, minor tweaks to existing copy, and fieldsets for grouping questions
I haven't updated the name of the files or classes here in order to keep things focused on the user-facing changes with minimal diff, but I have opened #1666 to do that as an optional extra

Update create new user request

---

app/models/support/requests/content_advice_request.rb
app/models/support/requests/content_change_request.rb
spec/features/content_change_requests_spec.rb

This pull request:
- changes the description of the content advice support form to add 'changes to content in history mode' to the content
- changes the title of the 'Request a content change or new content on GOV.UK' form to make it clearer it for mainstream content
- updates description of the 'Request a content change or new content on GOV.UK' form
https://trello.com/c/PV0dNaXe

Update title and descriptions of content advice and request forms

---

Gemfile
Gemfile.lock

We are currently using release tag `v8.0.0` of `jquery-ui-rails`, which has the gem version specified as 7.0.0.
This means our `Gemfile.lock` contains 7.0.0 and therefore dependabot keeps raising PRs to attempt to upgrade it.
Switching instead to the `v8.0.0-release` branch, which actually bumps the gem version to 8.0.0.

Use release branch of `jquery-ui-rails`

---

Gemfile
Gemfile.lock

Version 8.0.0 of the `jquery-ui-rails` gem was not previously released to RubyGems, so we specified a tag for the GitHub repo.
This version is now available, so we can switch to using RubyGems instead.
[Trello card](https://trello.com/c/CB1AbcRK)

Switch to RubyGems version of `jquery-ui-rails`

---

app/models/support/requests/technical_fault_report.rb

It's being retired
Trello: https://trello.com/c/MiBvG4Xs/3767-retire-contacts-admin

Remove Contacts Admin

---

app/models/zendesk/ticket/content_change_request_ticket.rb
config/zendesk/custom_fields_data.yml
spec/features/content_change_requests_spec.rb
spec/models/zendesk/ticket/content_change_request_ticket_spec.rb

Content Support have requested that the 'Which URLs are affected?' field on the content requests form should map to a custom Zendesk field.
This field has been set up in Zendesk by User Support with the ID 19824287274012.
Therefore adding this mapping into the request form.

[PP-7008] Add custom field for content requests form

---

app/views/support/emergency_contact_details.html.erb

This asks the user to check GOV.UK's statuspage before contacting the on-call team. This might save them a call, reassure them that the issue is being dealt with, and reduce distractions for the team. 

Add note about checking status page first

---

app/controllers/change_existing_user_requests_controller.rb
app/controllers/requests_controller.rb
app/helpers/errors_helper.rb
app/views/change_existing_user_requests/_request_details.html.erb
app/views/layouts/design_system.html.erb
app/views/requests/new.html.erb
app/views/support/_collaborators.html.erb
config/locales/en.yml
spec/helpers/errors_helper_spec.rb

- Add support for using the Design System for request forms (all but the last commit)
- Use the Design System for the "Change an existing user's account" form (final commit)
The former could be its own PR, but it probably makes more sense with the added context of the final commit
https://github.com/user-attachments/assets/fe4819e2-5ddb-4e00-872c-a7ab80e5dc52

[PP-7296] Design systemise change user form

---

app/views/report_an_issue_with_govuk_search_results_requests/_request_details.html.erb

Re-route the form to the Web Support group instead of the Performance Analytics group and remove the blue banner at the top of the form, which linked to the old evaluation tool.

[SCH-620] Update 'Report an issue with GOV.UK search results' support form
